---

- name: Get System fs.file-max
  become: yes
  ansible.builtin.command: sysctl -n fs.file-max
  register: sysctl_filemax
  changed_when: no

- name: Set System fs.file-max
  become: yes
  ansible.posix.sysctl:
    name: fs.file-max
    value: "{{ sansible_vernemq_nofile }}"
    sysctl_set: yes
    state: present
    reload: yes
  when: (sysctl_filemax.stdout | int) < sansible_vernemq_nofile

- name: Install VerneMQ from sansible_vernemq_download_url
  block:

    - name: Download VerneMQ .deb Package from sansible_vernemq_download_url
      ansible.builtin.get_url:
        url: "{{ sansible_vernemq_download_url }}"
        dest: "/tmp/{{ sansible_vernemq_download_url.split('/')[-1] }}"
      retries: 2
      register: ansible_vernemq_download
      until: ansible_vernemq_download is succeeded

    - name: Install VerneMQ .deb Package from sansible_vernemq_download_url
      ansible.builtin.apt:
        deb: "/tmp/{{ sansible_vernemq_download_url.split('/')[-1] }}"

  become: yes
  when: sansible_vernemq_download_url is not none

- name: Install VerneMQ from official Repository
  block:

    - name: Download VerneMQ .deb Package from official Repository
      ansible.builtin.get_url:
        dest: "/tmp/vernemq-{{ sansible_vernemq_version }}.{{ ansible_lsb.codename }}.x86_64.deb"
        url: "https://github.com/vernemq/vernemq/releases/download/{{ sansible_vernemq_version }}/vernemq-{{ sansible_vernemq_version }}.{{ ansible_lsb.codename }}.x86_64.deb"
      retries: 2
      register: ansible_vernemq_download
      until: ansible_vernemq_download is succeeded

    - name: Install VerneMQ .deb Package from official Repository
      ansible.builtin.apt:
        deb: "/tmp/vernemq-{{ sansible_vernemq_version }}.{{ ansible_lsb.codename }}.x86_64.deb"

  become: yes
  when: sansible_vernemq_download_url is none

- name: Set VerneMQ nofile limits.conf
  become: yes
  ansible.builtin.lineinfile:
    dest: /etc/security/limits.conf
    create: no
    regexp: "^vernemq\\s+{{ item }}\\s+nofile\\s+\\d+"
    line: "vernemq {{ item }} nofile {{ sansible_vernemq_nofile }}"
  with_items:
    - soft
    - hard

- name: Locate VerneMQ SystemdD conf
  ansible.builtin.shell: dpkg -L vernemq | grep vernemq.service
  register: sansible_vernemq_systemd_conf_file_location
  changed_when: no

- name: Add VerneMQ SystemD settings
  become: yes
  community.general.ini_file:
    option: "{{ item.key }}"
    path: "{{ sansible_vernemq_systemd_conf_file_location.stdout }}"
    section: Service
    value: "{{ item.value }}"
  with_dict:
    LimitNOFILE: "{{ sansible_vernemq_nofile }}"
  register: sansible_vernemq_systemd_conf_file

- name: Ensure VerneMQ SystemD service is updated
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - sansible_vernemq_systemd_conf_file.changed
  tags:
    - skip_ansible_lint
